spring.application.name=tracker-server

spring.datasource.url=jdbc:mysql://localhost:3306/tracker_db
spring.datasource.username=root
spring.datasource.password=Mahe@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=MahendarTrackerSecretKeyMahendarTrackerSecretKey12345
jwt.expiration=86400000